from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime
from .repository import Serializable, Repository
from typing import Self
import os
import subprocess
import re
from collections import defaultdict
from .architecture import Architecture
from typing import NamedTuple

class LatestSnapshotOption:
    """Snapshot list entry generating new snapshot with selected toolset (when project is created or build starts)."""
    name = "Get latest"
    short_details = "Generates new snapshot of the Gentoo ebuild repository with the toolset"
    icon_name = "folder-download-symbolic"

LATEST_SNAPSHOT = LatestSnapshotOption()

# Repository from which Catalyst generates snapshots (catalyst -s stable), they are named gentoo-<commit>.sqfs.
GENTOO_REPOSITORY_URL = "https://anongit.gentoo.org/git/repo/sync/gentoo.git"
GENTOO_REPOSITORY_BRANCH = "stable"

def latest_gentoo_commit(timeout: float = 30) -> str | None:
    """Current commit of branch from which Catalyst generates snapshots, None when it can't be checked."""
    try:
        output = subprocess.run(["git", "ls-remote", GENTOO_REPOSITORY_URL, f"refs/heads/{GENTOO_REPOSITORY_BRANCH}"],
                                capture_output=True, text=True, timeout=timeout).stdout
    except Exception as e:
        print(f"Failed to check latest Gentoo repository commit: {e}")
        return None
    commit = output.split()[0] if output.split() else ""
    return commit if re.fullmatch(r"[0-9a-f]{40}", commit) else None

def existing_latest_snapshot(log=print) -> Snapshot | None:
    """Snapshot generated from current commit of Gentoo repository, when it was already generated. Then it's used
    instead of generating it again (Catalyst downloads whole repository for it)."""
    commit = latest_gentoo_commit()
    if commit is None:
        log("Couldn't check latest commit of Gentoo repository, snapshot will be generated")
        return None
    filename = f"gentoo-{commit}.sqfs"
    snapshot = next((snapshot for snapshot in Repository.Snapshot.value
                     if snapshot.filename == filename and not snapshot.from_file), None)
    if snapshot is None or not os.path.isfile(snapshot.file_path()):
        log(f"Latest commit of Gentoo repository is {commit}, it has no snapshot yet")
        return None
    log(f"Snapshot of latest commit of Gentoo repository already exists: {filename} ({snapshot.name})")
    return snapshot

@dataclass
class Snapshot(Serializable):
    filename: str
    date: datetime | None
    from_file: bool = False # Added from file (not generated by Catalyst), it can contain own changes.
    def serialize(self) -> dict:
        return {
            "filename": self.filename,
            "date": self.date.isoformat() if self.date else None,
            "from_file": self.from_file
        }
    @classmethod
    def init_from(cls, data: dict) -> Self:
        return cls(
            filename=data["filename"],
            date=datetime.fromisoformat(data["date"]) if data.get("date") else None,
            from_file=bool(data.get("from_file", False))
        )

    @property
    def name(self) -> str:
        return self.date.strftime("%Y-%m-%d %H:%M") if self.date else "(Unknown date)"

    @property
    def short_details(self) -> str:
        return self.filename.rsplit('.', 1)[0]

    @property
    def may_contain_own_changes(self) -> bool:
        """Snapshot added from file, or found in snapshots folder with name not given by Catalyst (gentoo-<commit>)."""
        return self.from_file or re.fullmatch(r"gentoo-[0-9a-f]{40}\.sqfs", self.filename) is None

    def file_path(self) -> str:
        snapshots_location = os.path.realpath(os.path.expanduser(Repository.Settings.value.snapshots_location))
        return os.path.join(snapshots_location, self.filename)

    def load_ebuilds(self) -> dict[str, dict[str, list[str]]]:
        snapshot_file_path = self.file_path()

        try:
            output = subprocess.check_output(['unsquashfs', '-l', snapshot_file_path], text=True)
        except subprocess.CalledProcessError as e:
            print(f"Error reading {snapshot_file_path}: {e}")
            return {}

        nested_dict = defaultdict(lambda: defaultdict(list))

        for line in output.splitlines():
            line = line.strip()
            if not line.startswith('squashfs-root/'):
                continue

            path = line[len('squashfs-root/'):]
            if not path.endswith('.ebuild'):
                continue

            parts = path.split('/')
            if len(parts) < 3:
                continue  # Skip malformed paths

            category, package, filename = parts[:3]

            # Match version from filename: package-version.ebuild
            match = re.match(rf"^{re.escape(package)}-(.+)\.ebuild$", filename)
            if match:
                version = match.group(1)
                nested_dict[category][package].append(version)

        # Convert defaultdicts to normal dicts
        return {
            category: dict(sorted(packages.items()))
            for category, packages in sorted(nested_dict.items())
        }

    def load_profiles(self, arch: Architecture) -> list[PortageProfile]:
        # TODO: Needs additional mapping, doesnt work for example for ppc64le
        profiles_contents = subprocess.check_output(['unsquashfs', '-cat', self.file_path(), "profiles/profiles.desc"], text=True)
        return parse_profiles_desc(contents=profiles_contents, arch=arch, repo="gentoo")

def parse_profiles_desc(contents: str, arch: Architecture, repo: str) -> list[PortageProfile]:
    """Reads profiles of given arch from profiles.desc file contents (format: 'arch path stability')."""
    return [
        PortageProfile(path=parts[1], stability=parts[2], repo=repo)
        for line in contents.splitlines()
        if (parts := line.split()) and parts[0] == arch.value and len(parts) >= 3
    ]

class PortageProfile(Serializable):
    path: str
    stability: str
    repo: str # gentoo by default

    def __init__(self, path: str, stability: str, repo: str):
        self.path = path
        self.stability = stability
        self.repo = repo

    def __eq__(self, other):
        if not isinstance(other, PortageProfile):
            return NotImplemented
        return self.path == other.path and self.repo == other.repo

    def __hash__(self):
        return hash((self.path, self.repo))

    def serialize(self) -> dict:
        return {
            "path": self.path,
            "stability": self.stability,
            "repo": self.repo
        }
    @classmethod
    def init_from(cls, data: dict) -> Self:
        return cls(
            path=data["path"],
            stability=data["stability"],
            repo=data["repo"]
        )

